version: "3"

services:

  mongodb:
    image: mongo:4.4.2
    container_name: mongodb-cc
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb/db:/data/db
      - ./volumes/mongodb/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: cc_bot
      MONGO_INITDB_ROOT_PASSWORD: pa5sw0r4mdb
      MONGO_INITDB_DATABASE: cc-db
    networks:
      - cc-network
    user: root
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb-cc
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: ccdb
      INFLUXDB_ADMIN_USER: cc_bot
      INFLUXDB_ADMIN_PASSWORD: p4s5w0r4idb
    networks:
      - cc-network
    user: root
    restart: unless-stopped

  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana-cc
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    networks:
      - cc-network
    user: root
    restart: unless-stopped

networks:
  cc-network:
    external: true
